# Generated by Django 3.2.23 on 2025-09-26 17:46

from django.db import migrations, models
import teams.models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_code',
            field=models.CharField(default=teams.models.generate_team_id, max_length=36),
        ),
    ]
