# Generated by Django 3.2.23 on 2024-08-29 18:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0048_alter_volunteerapplication_night_shifts'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerapplication',
            name='disregarded',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Sí')], default=0),
        ),
        migrations.AlterField(
            model_name='hackerapplication',
            name='reimb_amount',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, 'Negative? Really? Please put a positive value'), django.core.validators.MaxValueValidator(200.0, 'Do not exceed the maximum amount of 200')]),
        ),
    ]
