# Generated by Django 3.2.23 on 2024-08-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0049_auto_20240829_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerapplication',
            name='disregarded',
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
