# Generated by Django 3.2.23 on 2024-08-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0050_auto_20240830_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorapplication',
            name='valid',
            field=models.BooleanField(default=False),
        ),
    ]
