# Generated by Django 3.2.23 on 2024-09-05 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0049_auto_20240830_1617'),
        ('applications', '0050_auto_20240830_1119'),
    ]

    operations = [
    ]
