# Generated by Django 3.2.23 on 2024-12-14 21:01

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0052_alter_mentorapplication_first_time_mentor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerapplication',
            name='fav_movie',
        ),
        migrations.AlterField(
            model_name='hackerapplication',
            name='graduation_year',
            field=models.IntegerField(choices=[(2024, '2024'), (2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029'), (2030, '2030'), (2031, '2031')], default=2025),
        ),
        migrations.AlterField(
            model_name='mentorapplication',
            name='first_time_mentor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mentorapplication',
            name='graduation_year',
            field=models.IntegerField(choices=[(2024, '2024'), (2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029'), (2030, '2030'), (2031, '2031')], default=2025),
        ),
        migrations.AlterField(
            model_name='mentorapplication',
            name='which_hack',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'HackUPC 2016 Fall'), (1, 'HackUPC 2016 Winter'), (2, 'HackUPC 2017 Fall'), (3, 'HackUPC 2017 Winter'), (4, 'HackUPC 2018'), (5, 'HackUPC 2019'), (6, 'HackUPC 2021'), (7, 'HackUPC 2022'), (8, 'HackUPC 2023'), (9, 'HackUPC 2024')], max_length=19, null=True),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='graduation_year',
            field=models.IntegerField(choices=[(2024, '2024'), (2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029'), (2030, '2030'), (2031, '2031')], default=2025),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='which_hack',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, 'HackUPC 2016 Fall'), (1, 'HackUPC 2016 Winter'), (2, 'HackUPC 2017 Fall'), (3, 'HackUPC 2017 Winter'), (4, 'HackUPC 2018'), (5, 'HackUPC 2019'), (6, 'HackUPC 2021'), (7, 'HackUPC 2022'), (8, 'HackUPC 2023'), (9, 'HackUPC 2024')], max_length=19),
        ),
    ]
