# Generated by Django 3.2.23 on 2024-12-31 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0053_auto_20241214_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerapplication',
            name='hobbies',
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='hear_about_us',
            field=models.CharField(choices=[('Posters', 'Posters'), ('Redes Sociales', 'Redes Sociales'), ('Mesas en el bar de la FIB', 'Mesas en el bar de la FIB'), ('Mensajes por grupos de Whatsapp', 'Mensajes por grupos de Whatsapp'), ('Amigos, compañeros u otras personas', 'Amigos, compañeros u otras personas'), ('Anuncios online', 'Anuncios online'), ('Otros', 'Otros')], default='', max_length=300),
        ),
    ]
