# Generated by Django 3.2.23 on 2025-01-30 10:48

import applications.models.base
import applications.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0055_auto_20250112_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackerapplication',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=applications.models.base.resume_path_hackers, validators=[applications.validators.validate_file_extension, applications.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='mentorapplication',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=applications.models.base.resume_path_mentors, validators=[applications.validators.validate_file_extension, applications.validators.validate_file_size]),
        ),
    ]
