# Generated by Django 3.2.23 on 2025-02-03 21:45

import applications.models.base
import applications.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0056_auto_20250130_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackerapplication',
            name='diet',
            field=models.CharField(choices=[('Select', '- Select a diet -'), ('None', 'No requirements'), ('Vegetarian', 'Vegetarian'), ('Vegan', 'Vegan'), ('Gluten-free', 'Gluten-free'), ('Others', 'Others')], default='None', max_length=300),
        ),
        migrations.AlterField(
            model_name='hackerapplication',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=applications.models.base.resume_path_hackers, validators=[applications.validators.validate_file_extension_size]),
        ),
        migrations.AlterField(
            model_name='hackerapplication',
            name='tshirt_size',
            field=models.CharField(choices=[('Select', '- Select a t-shirt size -'), ('XS', 'Unisex - XS'), ('S', 'Unisex - S'), ('M', 'Unisex - M'), ('L', 'Unisex - L'), ('XL', 'Unisex - XL'), ('XXL', 'Unisex - XXL'), ('XXXL', 'Unisex - XXXL')], default='Select', max_length=300),
        ),
        migrations.AlterField(
            model_name='mentorapplication',
            name='diet',
            field=models.CharField(choices=[('Select', '- Select a diet -'), ('None', 'No requirements'), ('Vegetarian', 'Vegetarian'), ('Vegan', 'Vegan'), ('Gluten-free', 'Gluten-free'), ('Others', 'Others')], default='None', max_length=300),
        ),
        migrations.AlterField(
            model_name='mentorapplication',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=applications.models.base.resume_path_mentors, validators=[applications.validators.validate_file_extension_size]),
        ),
        migrations.AlterField(
            model_name='mentorapplication',
            name='tshirt_size',
            field=models.CharField(choices=[('Select', '- Select a t-shirt size -'), ('XS', 'Unisex - XS'), ('S', 'Unisex - S'), ('M', 'Unisex - M'), ('L', 'Unisex - L'), ('XL', 'Unisex - XL'), ('XXL', 'Unisex - XXL'), ('XXXL', 'Unisex - XXXL')], default='Select', max_length=300),
        ),
        migrations.AlterField(
            model_name='sponsorapplication',
            name='diet',
            field=models.CharField(choices=[('Select', '- Select a diet -'), ('None', 'No requirements'), ('Vegetarian', 'Vegetarian'), ('Vegan', 'Vegan'), ('Gluten-free', 'Gluten-free'), ('Others', 'Others')], default='None', max_length=300),
        ),
        migrations.AlterField(
            model_name='sponsorapplication',
            name='tshirt_size',
            field=models.CharField(choices=[('Select', '- Select a t-shirt size -'), ('XS', 'Unisex - XS'), ('S', 'Unisex - S'), ('M', 'Unisex - M'), ('L', 'Unisex - L'), ('XL', 'Unisex - XL'), ('XXL', 'Unisex - XXL'), ('XXXL', 'Unisex - XXXL')], default='Select', max_length=300),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='tshirt_size',
            field=models.CharField(choices=[('Select', '- Select a t-shirt size -'), ('XS', 'Unisex - XS'), ('S', 'Unisex - S'), ('M', 'Unisex - M'), ('L', 'Unisex - L'), ('XL', 'Unisex - XL'), ('XXL', 'Unisex - XXL'), ('XXXL', 'Unisex - XXXL')], default='Select', max_length=300),
        ),
    ]
