# Generated by Django 3.2.23 on 2025-10-12 17:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0057_auto_20250203_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackerapplication',
            name='cv_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hackerapplication',
            name='diet',
            field=models.CharField(choices=[('', '- Select a diet -'), ('None', 'No requirements'), ('Vegetarian', 'Vegetarian'), ('Vegan', 'Vegan'), ('Gluten-free', 'Gluten-free'), ('Others', 'Others')], default='None', max_length=300),
        ),
        migrations.AlterField(
            model_name='hackerapplication',
            name='lennyface',
            field=models.CharField(default='-.-', max_length=20),
        ),
        migrations.AlterField(
            model_name='hackerapplication',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format:         '+#########'. Up to 16 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='hackerapplication',
            name='tshirt_size',
            field=models.CharField(choices=[('', '- Select a t-shirt size -'), ('XS', 'Unisex - XS'), ('S', 'Unisex - S'), ('M', 'Unisex - M'), ('L', 'Unisex - L'), ('XL', 'Unisex - XL'), ('XXL', 'Unisex - XXL'), ('XXXL', 'Unisex - XXXL')], default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='mentorapplication',
            name='diet',
            field=models.CharField(choices=[('', '- Select a diet -'), ('None', 'No requirements'), ('Vegetarian', 'Vegetarian'), ('Vegan', 'Vegan'), ('Gluten-free', 'Gluten-free'), ('Others', 'Others')], default='None', max_length=300),
        ),
        migrations.AlterField(
            model_name='mentorapplication',
            name='lennyface',
            field=models.CharField(default='-.-', max_length=20),
        ),
        migrations.AlterField(
            model_name='mentorapplication',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format:         '+#########'. Up to 16 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='mentorapplication',
            name='tshirt_size',
            field=models.CharField(choices=[('', '- Select a t-shirt size -'), ('XS', 'Unisex - XS'), ('S', 'Unisex - S'), ('M', 'Unisex - M'), ('L', 'Unisex - L'), ('XL', 'Unisex - XL'), ('XXL', 'Unisex - XXL'), ('XXXL', 'Unisex - XXXL')], default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='sponsorapplication',
            name='diet',
            field=models.CharField(choices=[('', '- Select a diet -'), ('None', 'No requirements'), ('Vegetarian', 'Vegetarian'), ('Vegan', 'Vegan'), ('Gluten-free', 'Gluten-free'), ('Others', 'Others')], default='None', max_length=300),
        ),
        migrations.AlterField(
            model_name='sponsorapplication',
            name='tshirt_size',
            field=models.CharField(choices=[('', '- Select a t-shirt size -'), ('XS', 'Unisex - XS'), ('S', 'Unisex - S'), ('M', 'Unisex - M'), ('L', 'Unisex - L'), ('XL', 'Unisex - XL'), ('XXL', 'Unisex - XXL'), ('XXXL', 'Unisex - XXXL')], default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='lennyface',
            field=models.CharField(default='-.-', max_length=20),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format:         '+#########'. Up to 16 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='tshirt_size',
            field=models.CharField(choices=[('', '- Select a t-shirt size -'), ('XS', 'Unisex - XS'), ('S', 'Unisex - S'), ('M', 'Unisex - M'), ('L', 'Unisex - L'), ('XL', 'Unisex - XL'), ('XXL', 'Unisex - XXL'), ('XXXL', 'Unisex - XXXL')], default='', max_length=300),
        ),
    ]
