# Generated by Django 3.2.23 on 2025-05-11 15:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0058_auto_20250511_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackerapplication',
            name='dubious_comment',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
