# Generated by Django 3.2.23 on 2025-12-09 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0058_auto_20251012_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerapplication',
            name='pronouns',
        ),
    ]
