# Generated by Django 3.2.23 on 2025-12-11 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0059_remove_volunteerapplication_pronouns'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackerapplication',
            name='kind_studies',
            field=models.CharField(choices=[('SECONDARY', 'Secondary Education - Baccalaureate'), ('VOCATIONAL', 'Vocational Training (FP)'), ('BACHELOR', 'Bachelor’s Degree'), ('MASTER', 'Master’s Degree'), ('OTHER', 'Other')], default='NA', max_length=300),
        ),
    ]
