# Generated by Django 3.2.23 on 2025-12-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0059_remove_volunteerapplication_pronouns'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerapplication',
            name='other_hear_about_us',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
