# Generated by Django 3.2.23 on 2025-12-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0059_remove_volunteerapplication_pronouns'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerapplication',
            name='studies_and_course',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
