# Generated by Django 3.2.23 on 2025-05-11 16:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0059_auto_20250511_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackerapplication',
            name='dubious_type',
            field=models.CharField(choices=[('OK', 'Not dubious'), ('INVALID_CV', 'Invalid CV'), ('LATE_GRAD', 'Invalid graduation year'), ('NOT_STUDENT', 'Not a student'), ('INVALID_SCHOOL', 'Invalid school'), ('OTHER', 'Other')], default='OK', max_length=300),
        ),
    ]
