# Generated by Django 3.2.23 on 2024-04-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0006_alter_reimbursement_reimbursed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursement',
            name='devpost_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
