# Generated by Django 3.2.23 on 2025-01-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0006_alter_reimbursement_reimbursed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursement',
            name='assigned_money',
            field=models.FloatField(default=0),
        ),
    ]
