# Generated by Django 3.2.23 on 2025-01-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0008_alter_reimbursement_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursement',
            name='assigned_money',
            field=models.FloatField(),
        ),
    ]
