# Generated by Django 3.2.23 on 2025-01-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0009_alter_reimbursement_assigned_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursement',
            name='assigned_money',
            field=models.FloatField(default=0),
        ),
    ]
