# Generated by Django 3.2.23 on 2025-01-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0011_alter_reimbursement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursement',
            name='devpost',
            field=models.URLField(blank=True, default='devpost.com', null=True),
        ),
    ]
