# Generated by Django 3.2.23 on 2025-01-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0012_reimbursement_devpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursement',
            name='devpost',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
