# Generated by Django 3.2.23 on 2025-10-24 14:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0013_alter_reimbursement_devpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursement',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 2, 16, 0, tzinfo=utc)),
        ),
    ]
