# Generated by Django 3.2.23 on 2026-02-19 17:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0014_alter_reimbursement_expiration_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursement',
            name='devpost_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 2, 16, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='status',
            field=models.CharField(choices=[('W', 'Wait listed'), ('PT', 'Pending receipt submission'), ('PA', 'Pending receipt approval'), ('A', 'Receipt approved'), ('X', 'Expired'), ('FS', 'Friend submission'), ('F', 'Reimbursement Approved'), ('PD', 'Pending demo validation'), ('I', 'Invalid')], default='PT', max_length=2),
        ),
    ]
